/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Warning = WarningNormalization | WarningInvalidDestination | WarningUnsupportedMemoType | WarningGeneric;

export interface Schema {
  spec_version: string;
  cases: {
    module: "detect" | "muxed_encode" | "muxed_decode" | "extract_routing";
    description: string;
    input: {
      [k: string]: unknown;
    };
    expected: {
      warnings?: Warning[];
      [k: string]: unknown;
    };
    tags: ("positive" | "negative" | "edge" | "interop" | "regression" | "scope-boundary")[];
    notes?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface WarningNormalization {
  code: "NON_CANONICAL_ADDRESS" | "NON_CANONICAL_ROUTING_ID";
  severity: "warn";
  message: string;
  normalization: {
    original: string;
    normalized: string;
  };
}
export interface WarningInvalidDestination {
  code: "INVALID_DESTINATION";
  severity: "error";
  message: string;
  context: {
    destinationKind: "C";
  };
}
export interface WarningUnsupportedMemoType {
  code: "UNSUPPORTED_MEMO_TYPE";
  severity: "warn";
  message: string;
  context: {
    memoType: "hash" | "return" | "unknown";
  };
}
export interface WarningGeneric {
  code:
    | "MEMO_IGNORED_FOR_MUXED"
    | "MEMO_PRESENT_WITH_MUXED"
    | "CONTRACT_SENDER_DETECTED"
    | "MEMO_TEXT_UNROUTABLE"
    | "MEMO_ID_INVALID_FORMAT";
  severity: "info" | "warn" | "error";
  message: string;
}
