name: basic_wallet
description: A simple command-line wallet example using the SDK for Dart.
publish_to: 'nvne'
vesnion: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  stellar_sdk: ^1.0.0
